CREATE TABLE IF NOT EXISTS coupon_campaigns (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  coupon_type VARCHAR(24) NOT NULL,
  threshold_cents BIGINT NOT NULL DEFAULT 0,
  discount_cents BIGINT NOT NULL,
  distribution_mode VARCHAR(24) NOT NULL DEFAULT 'PUBLIC_CLAIM',
  total_stock BIGINT UNSIGNED NOT NULL,
  issued_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  per_subject_limit INT UNSIGNED NOT NULL DEFAULT 1,
  claim_start_at DATETIME(3) NULL,
  claim_end_at DATETIME(3) NULL,
  validity_mode VARCHAR(24) NOT NULL DEFAULT 'RELATIVE_DAYS',
  valid_from DATETIME(3) NULL,
  valid_to DATETIME(3) NULL,
  valid_days INT UNSIGNED NOT NULL DEFAULT 30,
  order_types_json TEXT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_coupon_campaigns_tenant_id (tenant_id, id),
  KEY idx_coupon_campaigns_store_status (tenant_id, store_id, status, claim_start_at, claim_end_at),
  CONSTRAINT fk_coupon_campaigns_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_coupon_campaigns_store FOREIGN KEY (store_id) REFERENCES stores(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS customer_coupons (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  campaign_id BIGINT UNSIGNED NOT NULL,
  coupon_no VARCHAR(48) NOT NULL,
  customer_id BIGINT UNSIGNED NULL,
  subject_key_hash CHAR(64) COLLATE utf8mb4_bin NOT NULL,
  source VARCHAR(24) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'PROVISIONAL',
  campaign_snapshot_json TEXT NOT NULL,
  valid_from DATETIME(3) NOT NULL,
  valid_to DATETIME(3) NOT NULL,
  idempotency_key VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
  request_fingerprint CHAR(64) COLLATE utf8mb4_bin NOT NULL,
  claimed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  used_at DATETIME(3) NULL,
  voided_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_customer_coupons_no (tenant_id, coupon_no),
  UNIQUE KEY uk_customer_coupons_idempotency (tenant_id, idempotency_key),
  KEY idx_customer_coupons_campaign_subject (tenant_id, campaign_id, subject_key_hash, status),
  KEY idx_customer_coupons_customer (tenant_id, customer_id, status, valid_to),
  CONSTRAINT fk_customer_coupons_campaign FOREIGN KEY (tenant_id, campaign_id) REFERENCES coupon_campaigns(tenant_id, id),
  CONSTRAINT fk_customer_coupons_customer FOREIGN KEY (tenant_id, customer_id) REFERENCES customers(tenant_id, id),
  CONSTRAINT fk_customer_coupons_store FOREIGN KEY (store_id) REFERENCES stores(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS marketing_placements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  placement_code VARCHAR(32) NOT NULL DEFAULT 'HOME_POPUP',
  image_asset_id BIGINT UNSIGNED NULL,
  image_url VARCHAR(1024) NOT NULL,
  title VARCHAR(80) NOT NULL DEFAULT '',
  subtitle VARCHAR(200) NOT NULL DEFAULT '',
  action_type VARCHAR(32) NOT NULL DEFAULT 'NONE',
  action_target_id BIGINT UNSIGNED NULL,
  frequency VARCHAR(32) NOT NULL DEFAULT 'ONCE_PER_CAMPAIGN',
  priority INT NOT NULL DEFAULT 0,
  channel_scope VARCHAR(24) NOT NULL DEFAULT 'ALL',
  active_from DATETIME(3) NULL,
  active_to DATETIME(3) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_marketing_placements_tenant_id (tenant_id, id),
  KEY idx_marketing_placements_active (tenant_id, store_id, placement_code, status, active_from, active_to, priority),
  CONSTRAINT fk_marketing_placements_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_marketing_placements_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_marketing_placements_asset FOREIGN KEY (image_asset_id) REFERENCES media_assets(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS marketing_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  placement_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(24) NOT NULL,
  subject_key_hash CHAR(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  idempotency_key VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
  request_fingerprint CHAR(64) COLLATE utf8mb4_bin NOT NULL,
  occurred_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_marketing_events_idempotency (tenant_id, idempotency_key),
  KEY idx_marketing_events_placement (tenant_id, placement_id, event_type, occurred_at),
  CONSTRAINT fk_marketing_events_placement FOREIGN KEY (tenant_id, placement_id) REFERENCES marketing_placements(tenant_id, id),
  CONSTRAINT fk_marketing_events_store FOREIGN KEY (store_id) REFERENCES stores(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lottery_campaigns (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  channel_scope VARCHAR(24) NOT NULL DEFAULT 'ALL',
  active_from DATETIME(3) NOT NULL,
  active_to DATETIME(3) NOT NULL,
  daily_limit INT UNSIGNED NOT NULL DEFAULT 1,
  total_limit INT UNSIGNED NOT NULL DEFAULT 1,
  draw_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  terms TEXT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_lottery_campaigns_tenant_id (tenant_id, id),
  KEY idx_lottery_campaigns_active (tenant_id, store_id, status, active_from, active_to),
  CONSTRAINT fk_lottery_campaigns_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_lottery_campaigns_store FOREIGN KEY (store_id) REFERENCES stores(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lottery_prizes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  campaign_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  prize_type VARCHAR(24) NOT NULL,
  coupon_campaign_id BIGINT UNSIGNED NULL,
  weight BIGINT UNSIGNED NOT NULL,
  total_stock BIGINT UNSIGNED NOT NULL DEFAULT 0,
  awarded_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_lottery_prizes_tenant_id (tenant_id, id),
  KEY idx_lottery_prizes_campaign (tenant_id, campaign_id, status, sort_order),
  CONSTRAINT fk_lottery_prizes_campaign FOREIGN KEY (tenant_id, campaign_id) REFERENCES lottery_campaigns(tenant_id, id),
  CONSTRAINT fk_lottery_prizes_coupon FOREIGN KEY (tenant_id, coupon_campaign_id) REFERENCES coupon_campaigns(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lottery_draws (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  campaign_id BIGINT UNSIGNED NOT NULL,
  prize_id BIGINT UNSIGNED NULL,
  draw_no VARCHAR(48) NOT NULL,
  subject_key_hash CHAR(64) COLLATE utf8mb4_bin NOT NULL,
  business_date DATE NOT NULL,
  result_type VARCHAR(24) NOT NULL,
  result_reason VARCHAR(40) NOT NULL DEFAULT '',
  customer_coupon_id BIGINT UNSIGNED NULL,
  prize_snapshot_json TEXT NOT NULL,
  random_value BIGINT UNSIGNED NOT NULL,
  total_weight BIGINT UNSIGNED NOT NULL,
  idempotency_key VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
  request_fingerprint CHAR(64) COLLATE utf8mb4_bin NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_lottery_draws_no (tenant_id, draw_no),
  UNIQUE KEY uk_lottery_draws_idempotency (tenant_id, idempotency_key),
  KEY idx_lottery_draws_subject_day (tenant_id, campaign_id, subject_key_hash, business_date),
  KEY idx_lottery_draws_campaign (tenant_id, campaign_id, created_at),
  CONSTRAINT fk_lottery_draws_campaign FOREIGN KEY (tenant_id, campaign_id) REFERENCES lottery_campaigns(tenant_id, id),
  CONSTRAINT fk_lottery_draws_prize FOREIGN KEY (tenant_id, prize_id) REFERENCES lottery_prizes(tenant_id, id),
  CONSTRAINT fk_lottery_draws_coupon FOREIGN KEY (customer_coupon_id) REFERENCES customer_coupons(id),
  CONSTRAINT fk_lottery_draws_store FOREIGN KEY (store_id) REFERENCES stores(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
