CREATE TABLE IF NOT EXISTS order_table_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  related_order_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(24) NOT NULL,
  from_table_id BIGINT UNSIGNED NULL,
  from_table_name VARCHAR(120) NOT NULL DEFAULT '',
  to_table_id BIGINT UNSIGNED NULL,
  to_table_name VARCHAR(120) NOT NULL DEFAULT '',
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_order_table_events_order (tenant_id,order_id,created_at),
  KEY idx_order_table_events_related (tenant_id,related_order_id),
  CONSTRAINT fk_order_table_events_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_order_table_events_related_order FOREIGN KEY (related_order_id) REFERENCES orders(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_settlement_parts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  payment_id BIGINT UNSIGNED NOT NULL,
  part_no INT UNSIGNED NOT NULL,
  amount_cents BIGINT NOT NULL,
  method VARCHAR(24) NOT NULL,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  idempotency_key VARCHAR(128) NOT NULL,
  request_fingerprint VARCHAR(64) NOT NULL,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_order_settlement_idempotency (tenant_id,idempotency_key),
  UNIQUE KEY uk_order_settlement_part (tenant_id,order_id,part_no),
  KEY idx_order_settlement_order (tenant_id,order_id,created_at),
  CONSTRAINT fk_order_settlement_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_order_settlement_payment FOREIGN KEY (payment_id) REFERENCES payment_transactions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_return_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  order_item_id BIGINT UNSIGNED NOT NULL,
  sku_id BIGINT UNSIGNED NOT NULL,
  product_name_snapshot VARCHAR(120) NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  amount_cents BIGINT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  requested_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME(3) NULL,
  review_remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_order_return_requests_order (tenant_id,order_id,status,created_at),
  CONSTRAINT fk_order_return_requests_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_order_return_requests_item FOREIGN KEY (order_item_id) REFERENCES order_items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS offline_reconciliations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  business_date DATE NOT NULL,
  expected_cash_cents BIGINT NOT NULL DEFAULT 0,
  expected_external_cents BIGINT NOT NULL DEFAULT 0,
  actual_cash_cents BIGINT NOT NULL DEFAULT 0,
  actual_external_cents BIGINT NOT NULL DEFAULT 0,
  discrepancy_cents BIGINT NOT NULL DEFAULT 0,
  note VARCHAR(500) NOT NULL DEFAULT '',
  status VARCHAR(24) NOT NULL DEFAULT 'CONFIRMED',
  confirmed_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  confirmed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_offline_reconciliation_date (tenant_id,store_id,business_date),
  KEY idx_offline_reconciliation_store (tenant_id,store_id,business_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
