CREATE TABLE IF NOT EXISTS wechat_pay_onboarding_applications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  subject_type VARCHAR(24) NOT NULL DEFAULT 'MICRO',
  business_scene VARCHAR(24) NOT NULL DEFAULT 'STORE',
  merchant_short_name VARCHAR(64) NOT NULL DEFAULT '',
  service_phone VARCHAR(32) NOT NULL DEFAULT '',
  business_address VARCHAR(500) NOT NULL DEFAULT '',
  operator_name VARCHAR(80) NOT NULL DEFAULT '',
  contact_phone VARCHAR(32) NOT NULL DEFAULT '',
  contact_email VARCHAR(160) NOT NULL DEFAULT '',
  license_number VARCHAR(64) NOT NULL DEFAULT '',
  qualification_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  identity_material_ready TINYINT(1) NOT NULL DEFAULT 0,
  settlement_account_ready TINYINT(1) NOT NULL DEFAULT 0,
  business_material_ready TINYINT(1) NOT NULL DEFAULT 0,
  application_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  platform_note VARCHAR(1000) NOT NULL DEFAULT '',
  submitted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_wechat_onboarding_tenant (tenant_id),
  KEY idx_wechat_onboarding_status (application_status, updated_at),
  CONSTRAINT fk_wechat_onboarding_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
