CREATE TABLE IF NOT EXISTS customer_account_payment_intents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  business_type VARCHAR(32) NOT NULL,
  business_id BIGINT UNSIGNED NOT NULL,
  business_snapshot_json TEXT NOT NULL,
  amount_cents BIGINT NOT NULL,
  gift_cents BIGINT NOT NULL DEFAULT 0,
  provider VARCHAR(32) NOT NULL,
  merchant_no VARCHAR(64) NOT NULL DEFAULT '',
  sub_appid VARCHAR(64) NOT NULL DEFAULT '',
  customer_openid VARCHAR(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  provider_request_no VARCHAR(64) NOT NULL,
  provider_order_no VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  raw_response TEXT NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  request_fingerprint CHAR(64) NOT NULL,
  paid_at DATETIME(3) NULL,
  fulfilled_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_customer_account_payment_idempotency (tenant_id,idempotency_key),
  UNIQUE KEY uk_customer_account_payment_request (provider,provider_request_no),
  UNIQUE KEY uk_customer_account_payment_provider_order (provider,provider_order_no),
  KEY idx_customer_account_payment_customer (tenant_id,customer_id,created_at),
  KEY idx_customer_account_payment_business (tenant_id,business_type,business_id,status),
  CONSTRAINT fk_customer_account_payment_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_customer_account_payment_customer FOREIGN KEY (tenant_id,customer_id) REFERENCES customers(tenant_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_balance_payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  principal_cents BIGINT NOT NULL DEFAULT 0,
  bonus_cents BIGINT NOT NULL DEFAULT 0,
  amount_cents BIGINT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'APPLIED',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_order_balance_payment_order (tenant_id,order_id),
  KEY idx_order_balance_payment_customer (tenant_id,customer_id,created_at),
  CONSTRAINT fk_order_balance_payment_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_order_balance_payment_customer FOREIGN KEY (tenant_id,customer_id) REFERENCES customers(tenant_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
